import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PageHeader, StatusBadge } from '@/shared/components/layout';
import { Button, PermissionButton } from '@/shared/components/ui';
import { platformClient } from '@/lib/api/platformClient';
import { ApiError } from '@/lib/api/apiError'; import { relationshipValue } from '@/shared/utils/relationshipDisplay';

const err = (e: unknown) => e instanceof ApiError ? e.message : e instanceof Error ? e.message : 'Request failed.';
const enc = (v: string) => encodeURIComponent(v);
const reportCodes = ['tenant-status', 'plan-performance', 'revenue', 'invoice-aging', 'payment-failures', 'coupon-usage', 'tenant-usage', 'support-sla', 'security-events'];

export function PlatformRemoteLoginPage() {
  const [page, setPage] = useState(1); const [tenant, setTenant] = useState(''); const [reason, setReason] = useState(''); const [duration, setDuration] = useState('30'); const [showStart, setShowStart] = useState(false); const client = useQueryClient();
  const list = useQuery({ queryKey: ['remote-login-sessions', page], queryFn: async () => { const r = await platformClient.get<any[]>('/remote-login-sessions', { query: { page, per_page: 25 } as any }); return { data: r.data || [], meta: r.meta }; } });
  const start = useMutation({ mutationFn: () => platformClient.post('/tenants/' + enc(tenant) + '/impersonate', { reason, duration_minutes: Number(duration) }), onSuccess: () => { setShowStart(false); setTenant(''); setReason(''); void client.invalidateQueries({ queryKey: ['remote-login-sessions'] }); } });
  const end = useMutation({ mutationFn: (uuid: string) => platformClient.post('/remote-login-sessions/' + enc(uuid) + '/end', {}), onSuccess: () => void client.invalidateQueries({ queryKey: ['remote-login-sessions'] }) });
  const rows = list.data?.data || []; const meta = list.data?.meta;
  return <section className="enterprise-module-page platform-operations-page"><PageHeader title="Remote Login" description="Start and monitor remote-login sessions. Tenant acceptance and browser handoff are not available yet." actions={<PermissionButton guard="platform" permission="tenant.impersonate" type="button" onClick={() => setShowStart(true)}>Request remote access</PermissionButton>} />
    {list.isError ? <div className="surface-error">{err(list.error)}</div> : null}
    <div className="dashboard-panel"><table className="data-table"><thead><tr><th>Tenant</th><th>Platform operator</th><th>Target user</th><th>Reason</th><th>Expires</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.uuid}><td>{row.tenant_name || row.organization_name || 'Tenant'}</td><td>{row.platform_user_name || row.actor_name || 'Platform operator'}</td><td>{row.target_user_name || row.user_name || 'Owner'}</td><td>{row.reason}</td><td>{row.expires_at || '-'}</td><td><StatusBadge>{row.status}</StatusBadge></td><td>{row.status === 'active' ? <PermissionButton guard="platform" permission="tenant.impersonate" type="button" size="sm" variant="danger" disabled={end.isPending} onClick={() => end.mutate(row.uuid)}>End</PermissionButton> : '-'}</td></tr>)}</tbody></table><Pager page={page} meta={meta} onPage={setPage} /></div>
    {showStart ? <div className="dashboard-panel"><PageHeader title="Request remote access" description="The returned session records intent only; no tenant token or redirect is issued." /><form className="enterprise-form" onSubmit={(e) => { e.preventDefault(); start.mutate(); }}><label>Tenant UUID<input required value={tenant} onChange={(e) => setTenant(e.target.value)} /></label><label>Reason<textarea required minLength={5} value={reason} onChange={(e) => setReason(e.target.value)} /></label><label>Duration minutes<input required type="number" min="5" max="240" value={duration} onChange={(e) => setDuration(e.target.value)} /></label>{start.error ? <div className="surface-error">{err(start.error)}</div> : null}<footer className="enterprise-form__footer"><Button type="button" variant="secondary" onClick={() => setShowStart(false)}>Cancel</Button><PermissionButton guard="platform" permission="tenant.impersonate" type="submit" disabled={start.isPending}>{start.isPending ? 'Starting...' : 'Start session'}</PermissionButton></footer></form></div> : null}</section>;
}

export function PlatformReportsPage() {
  const [code, setCode] = useState(reportCodes[0]); const [page, setPage] = useState(1); const [format, setFormat] = useState('csv'); const client = useQueryClient();
  const report = useQuery({ queryKey: ['platform-report', code], queryFn: async () => (await platformClient.get<{ report: string; data: Array<Record<string, unknown>>; filters: Record<string, unknown> }>('/reports/' + code)).data });
  const jobs = useQuery({ queryKey: ['report-export-jobs', page], queryFn: async () => { const r = await platformClient.get<any[]>('/reports/export-jobs', { query: { page, per_page: 25 } as any }); return { data: r.data || [], meta: r.meta }; } });
  const exportJob = useMutation({ mutationFn: () => platformClient.post('/reports/' + code + '/export', { format }), onSuccess: () => void client.invalidateQueries({ queryKey: ['report-export-jobs'] }) });
  const rows = report.data?.data || []; const columns = rows.length ? Object.keys(rows[0]) : []; const meta = jobs.data?.meta;
  return <section className="enterprise-module-page platform-operations-page"><PageHeader title="Reports" description="View supported platform reports and queue asynchronous exports." /><div className="dashboard-panel"><div className="enterprise-form__grid"><label>Report<select value={code} onChange={(e) => setCode(e.target.value)}>{reportCodes.map((item) => <option key={item}>{item}</option>)}</select></label><label>Export format<select value={format} onChange={(e) => setFormat(e.target.value)}><option>csv</option><option>xlsx</option><option>json</option></select></label></div><PermissionButton guard="platform" permission="report.export" type="button" disabled={exportJob.isPending} onClick={() => exportJob.mutate()}>Queue export</PermissionButton>{exportJob.error ? <div className="surface-error">{err(exportJob.error)}</div> : null}<h3>{code}</h3>{report.isError ? <div className="surface-error">{err(report.error)}</div> : null}<ResourceTable rows={rows} columns={columns} /></div><div className="dashboard-panel"><PageHeader title="Export jobs" description="Jobs are asynchronous; download becomes available only after completion and a file is attached." /><ResourceTable rows={jobs.data?.data || []} columns={['report_code', 'format', 'status', 'created_at']} /><Pager page={page} meta={meta} onPage={setPage} /></div></section>;
}

function ResourceTable({ rows, columns }: { rows: Array<Record<string, unknown>>; columns: string[] }) { return rows.length ? <table className="data-table"><thead><tr>{columns.map((c) => <th key={c}>{c.replace(/_/g, ' ')}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={String(row.id || row.uuid || i)}>{columns.map((c) => <td key={c}>{String(relationshipValue(row, c, row[c]) ?? '-')}</td>)}</tr>)}</tbody></table> : <div className="empty-state">No data returned.</div>; }
function Pager({ page, meta, onPage }: { page: number; meta?: { last_page?: number; total?: number }; onPage: (n: number) => void }) { return <footer className="enterprise-form__footer"><span>{meta?.total || 0} record(s)</span><span><Button size="sm" variant="secondary" disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</Button>{' '}<Button size="sm" variant="secondary" disabled={page >= (meta?.last_page || 1)} onClick={() => onPage(page + 1)}>Next</Button></span></footer>; }
